snelusha/noto

commands/config.ts, commands/generate.ts, commands/prev.ts, src/cli.ts, src/utils.ts
=> feat: refactor commands

src/ai.ts, src/git.ts
=> feat: add hardcoded message to the first commit

src/git.ts
=> feat: filter lock files from staged diff

packages/cli/src/commands/noto.ts, packages/cli/src/commands/prev.ts
=> feat: add edit flag to noto and prev commands

packages/cli/src/ai/index.ts, packages/cli/src/commands/noto.ts
=> feat: add type option to generate commit message based on type

packages/cli/src/utils/git.ts, packages/cli/test/git.test.ts
=> fix: ignore lock files

packages/cli/src/commands/noto.ts, packages/cli/src/middleware/git.ts, packages/cli/src/utils/git.ts
=> feat: add push option to noto command

packages/cli/src/commands/checkout.ts, packages/cli/src/commands/index.ts, packages/cli/src/utils/git.ts
=> feat: add `checkout` command

packages/cli/src/ai/models.ts, packages/cli/src/ai/types.ts
=> feat: update available models

packages/cli/src/commands/branch.ts
=> feat: add `--all` branch to select all branches except the current

apps/web/package.json, bun.lock, packages/cli/package.json, packages/cli/src/ai/models.ts, packages/cli/src/ai/types.ts
=> feat: add `gemini-2.0-flash-lite` model

packages/cli/src/commands/branch.ts
=> feat: add force and all options to branch command

packages/cli/README.md, packages/cli/src/middleware/auth.ts
=> fix: prioritize environment variable for api key and update docs

apps/web/package.json, bun.lock, package.json, packages/cli/README.md, packages/cli/package.json, packages/cli/src/commands/noto.ts
=> feat: enable interactive editing mode by default

packages/cli/src/ai/models.ts, packages/cli/src/ai/types.ts
=> feat: add `gemini-2.5-flash-preview-04-17` model

apps/web/app/page.tsx, apps/web/components/github-stars.tsx, apps/web/components/npm-downloads.tsx
=> fix: remove outline from links

apps/web/package.json, bun.lock, package.json, packages/cli/package.json, packages/cli/src/ai/models.ts, packages/cli/src/ai/types.ts, packages/cli/src/commands/config.ts
=> feat: add `gemini-2.5-pro-preview-05-06` model with confirmation

apps/web/package.json, bun.lock, packages/cli/package.json, packages/cli/src/ai/models.ts, packages/cli/src/ai/types.ts
=> refactor: remove deprecated model `gemini-2.5-pro-preview-03-25`

packages/cli/src/commands/checkout.ts, packages/cli/src/utils/git.ts
=> feat: checkout new branch

packages/cli/src/commands/noto.ts
=> feat: add manual commit message input option

bun.lock, packages/cli/bunup.config.ts, packages/cli/package.json, packages/cli/tsup.config.ts
=> feat: migrate to bunup

packages/cli/src/commands/checkout.ts
This pull request updates the `checkout` command in the CLI to improve how new branch creation is handled. The main change is that the `--create` (or `-b`) flag can now accept either a boolean or a string, allowing users to specify the new branch name directly with the flag. The code is also refactored to consistently use a new `targetBranch` variable, simplifying branch operations and error handling.
Enhancements to branch creation and checkout logic:
* The `create` input parameter now accepts either a boolean or a string, allowing users to specify the new branch name directly via the `--create`/`-b` flag. (`packages/cli/src/commands/checkout.ts`)
* Introduced a `targetBranch` variable to unify logic for both creating and checking out branches, reducing code duplication and improving …
=> fix: allow string for create flag in checkout command
